BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'

            Button:
                text: 'Down'

    Button:
        text: 'Convert miles to km'

    Label:
        text: ''
        color: (255, 255, 0, 1)